[build-system]
requires = ["setuptools", "wheel", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "gchapero-models"
dynamic = ["version"]
dependencies = [
	"torch",
	"lightning",
	"torchmetrics",
	"torchvision",
	"click",
]
requires-python = ">=3.8"
